[2025-03-22T16:27:39.552+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T16:27:39.558+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.create_tables scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T16:27:39.562+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.create_tables scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T16:27:39.563+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-03-22T16:27:39.572+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_tables> on 2025-03-21 00:00:00+00:00
[2025-03-22T16:27:39.574+0000] {standard_task_runner.py:72} INFO - Started process 108229 to run task
[2025-03-22T16:27:39.576+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_pipeline', 'create_tables', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpuakqs0ix']
[2025-03-22T16:27:39.578+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask create_tables
[2025-03-22T16:27:39.601+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_pipeline.create_tables scheduled__2025-03-21T00:00:00+00:00 [running]> on host usmail-ThinkBook-14-G2-ITL
[2025-03-22T16:27:39.631+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T16:27:39.631+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T16:27:39.657+0000] {hive.py:475} INFO - USE `None`
[2025-03-22T16:27:39.677+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/system_fraud_transactions_detection/airflow_home/dags/dags.py", line 120, in create_tables
    conn = hive.Connection(host=localhost, port=port, username=username, database=database,password=password,auth=auth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 282, in __init__
    cursor.execute('USE `{}`'.format(database))
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10072, errorMessage='Error while compiling statement: FAILED: SemanticException [Error 10072]: Database does not exist: None'), operationHandle=None)
[2025-03-22T16:27:39.681+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=create_tables, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250322T162739, end_date=20250322T162739
[2025-03-22T16:27:39.693+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T16:27:39.694+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task create_tables (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10072, errorMessage='Error while compiling statement: FAILED: SemanticException [Error 10072]: Database does not exist: None'), operationHandle=None); 108229)
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/system_fraud_transactions_detection/airflow_home/dags/dags.py", line 120, in create_tables
    conn = hive.Connection(host=localhost, port=port, username=username, database=database,password=password,auth=auth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 282, in __init__
    cursor.execute('USE `{}`'.format(database))
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10072, errorMessage='Error while compiling statement: FAILED: SemanticException [Error 10072]: Database does not exist: None'), operationHandle=None)
[2025-03-22T16:27:39.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-22T16:27:39.719+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T16:27:39.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
